Fifa2018
mdrmuhaimin/ML_726_Project pull request #5
Opened 2017-11-29 01:24 UTC by vladymyrkozyr

In file filtered_fifa2018_players.csv you can see all useful information about players, including their ID

2017-11-29 12:00 UTC, mdrmuhaimin reviewed
Add .suo file to gitignore

2017-11-29 12:00 UTC, mdrmuhaimin commented on Fifa2018/Extract FIFA2018 Useful Data.sln
> +﻿
Please add this file to .gitignore

2017-11-29 12:04 UTC, mdrmuhaimin requested changes

2017-11-29 12:04 UTC, mdrmuhaimin commented on Fifa2018/Extract FIFA2018 Useful Data/Extract FIFA2018 Useful Data.pyproj
> +<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="4.0">
Do you really need this file to run it? If not can you please add it to .gitignore

2017-11-29 12:04 UTC, mdrmuhaimin commented on Fifa2018/Extract FIFA2018 Useful Data/Extract_FIFA2018_Useful_Data.py
> +english_premier_league_players = fifa2018[fifa2018['league'] == 'English Premier League']
Once you filtered by ID it will automatically select the needed player. You don't need this. And this will actually create an error.  For example, if a player is in EPL in Fifa 2017 but not in Fifa 18 we still need him but this actually omit players that are in Fifa 2017 but not in Fifa 2018

2017-11-29 12:04 UTC, mdrmuhaimin commented on Fifa2018/Extract FIFA2018 Useful Data/Extract_FIFA2018_Useful_Data.py
> +english_premier_league_players = fifa2018[fifa2018['league'] == 'English Premier League']
So please remove this line

2017-11-29 17:10 UTC, vladymyrkozyr commented
I corrected everything you said. Now you can accept merge request.

2017-11-30 00:07 UTC, mdrmuhaimin approved these changes

2017-11-30 00:07 UTC, merged